Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 32400, host: 32400

  config.vm.network "private_network", ip: "192.168.56.123"

  config.vm.provider "virtualbox" do |v|
  # v.gui = true
    v.name = "PlexVagrant"
    v.memory = "2048"
  end
  
  config.vm.provision :shell, :path => "InstallPlex.sh"
  
end
