Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/xenial64"

  config.ssh.insert_key = false
  
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 32400, host: 32400

  config.vm.network "public_network", ip: "192.168.188.123"

  config.vm.provider "virtualbox" do |v|
  # v.gui = true
    v.name = "PlexVagrant"
    v.memory = "2048"
  end
  
end
